
# Do NOT edit this file. Instead, just call it from the command line,
# using the instructions in the assignment notebook.

import sys
questions = sys.argv[1:]


valid_ids = ['q0']
break_flag = False
invalid_ids = []
for question in questions:
    if question != 'all' and question not in valid_ids:
        invalid_ids.append(question)

if len(invalid_ids) > 0:
    print(str(invalid_ids) + ' is/are not a valid question number(s). The possible question numbers are ' + str(valid_ids) + '.')
    sys.exit()

# Initialize Otter
import otter
grader = otter.Notebook("lab.ipynb")

# %load_ext autoreload
# %autoreload 2

# from lab import *

from pathlib import Path
import io
import pandas as pd
import numpy as np
np.set_printoptions(legacy='1.21')

# The cells below are here for you to write scratch work in. 
# You should write the code for your answer in `lab.py`, not here, but you can
# call your env_check function see its output and make sure it works.
# For example:

env_check()



if 'q0' in questions or questions == [] or 'all' in questions:
    print(grader.check("q0"))



